# Generated by Django 4.1.3 on 2022-11-20 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
